name = "Herring Cove"
description = "Herring Cove is ported from the jekyll theme of the same name"
license = "MIT"
tags = ["blog", "company"]

[author]
    name = "spf13"
    homepage = "http://spf13.com"

# If Porting existing theme
[original]
    author =  "arnp"
    repo = "http://www.github.com/arnp/herring-cove"
